{% set name = "jaraco.docker" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jaraco_docker-{{ version }}.tar.gz
  sha256: 6c7fa87f7f69cd18265882aac91db33ad2ed9198bcd51acf1b06c97582d1aff4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.2
    - setuptools-scm >=3.4.1
    - pip
  run:
    - python >=3.8
    - jaraco.functools
    - jaraco.context

test:
  imports:
    - jaraco.docker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jaraco/jaraco.docker
  dev_url: https://github.com/jaraco/jaraco.docker
  doc_url: https://github.com/jaraco/jaraco.docker
  summary: Docker facilities
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AlbertDeFusco
